server.servlet-path: /

spring.jersey.application-path: /api
spring.data.mongodb.uri: mongodb://localhost:27017/dev3

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true
